### ISSUE TITLE
Thinking beyond

### ISSUE THREAD

**Issue by passabilities** [donbobvanbirt/coin-ticker#11]
As I said previously, I am working on another project to accomplish the same thing but with a much wider range of functions (i.e. ticker, depth, buy, sell, pairs, assets, etc.). Right now, I'm using both what I have built and fetching the tickers from here (didn't want to add the tickers since it was already done here). How do you feel about a complete rewrite of the project or creation of a new one to incorporate this? I was thinking about starting a new project and calling it **crypto-exchange** for this but I don't want to take away from what you've already built though.

**Comment by passabilities** [comment]
I went ahead and created a repo for what I have. Not as many exchanges as you have, but I plan on adding more very soon. Also just need to add the ticker methods.

You can check it out here: https://github.com/passabilities/crypto-exchange

**Comment by donbobvanbirt** [comment]
Looks great @passabilities! Feel free to fork this project and use the code here.
